config/routes.rb
Rails.application.routes.draw do

  #devise_for :users
  devise_for :users, :controllers => { registrations: 'users/registrations'}

  root 'home#index'
  get 'home/index'
  get 'activity', to: 'home#activity'
  get 'analytics', to: 'home#analytics'
  get 'privacy_policy', to: 'home#privacy_policy'

  resources :enrollments do
    get :my, on: :collection
  end
  resources :tags, only: [:create, :index, :destroy]

  resources :courses, except: [:edit] do
    get :learning, :pending_review, :teaching, :unapproved, on: :collection
    member do
      get :analytics
      patch :approve
      patch :unapprove
    end
    resources :lessons, except: [:index] do
      resources :comments, except: [:index]
      put :sort
      member do
        delete :delete_video
      end
    end
    resources :enrollments, only: [:new, :create]
    resources :course_wizard, controller: 'courses/course_wizard'
  end

  resources :users, only: [:index, :edit, :show, :update]

  resources :enrollments do
    get :my, on: :collection
    member do
      get :certificate
    end
  end

  namespace :charts do
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'course_popularity'
    get 'money_makers'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index, :privacy_policy]
  def index
    @latest_good_reviews = Enrollment.reviewed.latest_good_reviews
    @latest = Course.latest.published.approved
    @top_rated = Course.top_rated.published.approved
    @popular = Course.popular.published.approved
    if current_user
      @learning_courses = Course.joins(:enrollments).where(enrollments: {user: current_user}).order(created_at: :desc).limit(3)
      @teaching_courses = current_user.courses
    end
    @popular_tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc).limit(10)

  end

  def activity
    if current_user.has_role?(:admin)
      @pagy, @activities = pagy(PublicActivity::Activity.all.order(created_at: :desc))
    else
      redirect_to root_path, alert: "You are not authorized to access this page"
    end
  end

  def analytics
    unless current_user.has_role?(:admin)
      redirect_to root_path, alert: "You are not authorized to access this page"
    end
  end

  def privacy_policy
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/activity.html.haml
- content_for :title do
  Corsego
  \|
  Activity

%h3
  .text-center
    Activity
    .badge.badge-info
      = @activities.count
%p

%ul.list-group
  - @activities.each do |activity|
    %li.list-group-item
      = activity.created_at.strftime('%d-%m-%Y %H:%m')
      (#{time_ago_in_words(activity.created_at)})
      = model_label(activity.trackable_type)
      = activity.trackable_type
      - if activity.trackable_type == "Lesson"
        - if Lesson.where(id: activity.trackable_id).present?
          = link_to activity.trackable, course_lesson_path(activity.trackable.course, activity.trackable)
        - else
          was deleted
      - elsif activity.trackable_type == "Comment"
        - if Comment.where(id: activity.trackable_id).any?
          = link_to activity.trackable.content, course_lesson_path(activity.trackable.lesson.course, activity.trackable.lesson)
        - else
          was deleted
      - else
        = link_to activity.trackable, activity.trackable
      = activity.key
      = crud_label(activity.key.match(/\.(.*)/)[1])


      by
      = link_to activity.owner, user_path(activity.owner)
      - if activity.parameters.any?
        = activity.parameters

!= pagy_bootstrap_nav(@pagy)
%br

app/views/home/analytics.html.haml
- content_for :title do
  Corsego
  \|
  Analytics


%h4.text-center
  New users per day
= line_chart charts_users_per_day_path

%h4.text-center
  New enrollments per day
= column_chart charts_enrollments_per_day_path

%h4.text-center
  Most enrolled courses

/= pie_chart @courses.group(:enrollments_count).count
/= pie_chart @enrollments.joins(:course).group(:'courses.title').count
= bar_chart charts_course_popularity_path

%h4.text-center
  Most paid courses
= bar_chart charts_money_makers_path

app/views/home/index.html.haml
- content_for :title do
  Corsego
  \|
  Online Courses - Learn Anything, On Your Schedule

.jumbotron.shadow
  .display-4
    What do you want to learn today?

  .p-4

  - if current_user
    = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
      .input-group
        = f.search_field :title_cont, class: 'form-control-lg', style: 'float: left; width: 175px; ', placeholder: 'Find a course', :autocomplete => :off
        %span.input-group-append
          %button.btn.btn-primary.btn-lg{:type => "submit"}
            %span.fa.fa-search{"aria-hidden" => "true"}
  - else
    %h4 Join to access all the courses
    = link_to 'Register', new_user_registration_path, class: 'btn btn-outline-custompurple btn-lg'
    = link_to 'Login', new_user_session_path, class: 'btn btn-outline-custompurple btn-lg'
    = link_to user_google_oauth2_omniauth_authorize_path, class: 'btn btn-outline-custompurple btn-lg' do
      .fab.fa-google


.card-group.shadow
  .card
    .card-body
      %h1
        .fa.fa-graduation-cap
      = pluralize(Course.approved.published.count, 'online courses')
      /= Course.count
      /online courses
      .row
      %small Explore a variety of fresh topics
  .card
    .card-body
      %h1
        .fa.fa-chalkboard-teacher
        /.fa.fa-brain
      = pluralize(Course.distinct.count(:user_id), 'expert instructors')
      /= Course.distinct.count(:user_id)
      /expert instructors
      .row
      %small Find the right instructor for you
  .card
    .card-body
      %h1
        .fa.fa-user-graduate
      = pluralize(User.count, 'active learners')
      /= User.count
      /active learners
      .row
      %small Join the knowledge sharing community
  .card
    .card-body
      %h1
        .fa.fa-infinity
      Lifetime access
      .row
      %small Learn on your schedule

%p

%h2
  .fa.fa-tags
  Top Categories
- @popular_tags.each do |tag|
  = link_to courses_path(courses_search: {course_tags_tag_id_eq: tag.id}) do
    .mt-1.btn.btn-info
      = tag.name
      %span.badge.badge-light
        = tag.course_tags_count
%hr

- if current_user
  - if current_user.enrollments.any?
    %h2
      .fa.fa-user-graduate
      = link_to 'Continue learning ', learning_courses_path
    .row
      - @learning_courses.each do |course|
        .col-md-6
          = render 'courses/course', course: course
          %p
    %hr
  - if current_user.courses.any?
    %h2
      .fa.fa-chalkboard-teacher
      = link_to 'You are teaching', teaching_courses_path
    .row
      - @teaching_courses.each do |course|
        .col-md-6
          = render 'courses/course', course: course
          %p
    %hr

%h2
  .fa.fa-chart-line
  = link_to 'Popular courses', courses_path(courses_search: {s: 'enrollments_count desc'})
.row
  - @popular.each do |course|
    .col-md-6
      = render 'courses/course', course: course
      %p
%hr
%h2
  .fa.fa-star
  = link_to 'Top rated courses', courses_path(courses_search: {s: 'average_rating desc'})
.row
  - @top_rated.each do |course|
    .col-md-6
      = render 'courses/course', course: course
      %p
%hr
%h2
  .fa.fa-clock
  = link_to 'Latest courses', courses_path(courses_search: {s: 'created_at desc'})
.row
  - @latest.each do |course|
    .col-md-6
      = render 'courses/course', course: course
      %p
%hr

%h2
  .fa.fa-comment
  What our students have to say
.row
  - @latest_good_reviews.each do |enrollment|
    .col-md-6
      = render 'enrollments/enrollment', enrollment: enrollment
      %p
%br
.card-group.shadow
  .card
    .card-body
      %b
        .fa.fa-clock
        Go at your own pace
      %small
        Enjoy lifetime access to courses on Udemy’s website and app
  .card
    .card-body
      %b
        .far.fa-check-circle
        Learn from industry experts
      %small
        Select from top instructors around the world
  .card
    .card-body
      %b
        .far.fa-play-circle
        Find video courses on almost any topic
      %small
        Build your library for your career and personal growth

app/views/home/privacy_policy.html.haml
%h2 Privacy Policy
%p
  Your privacy is important to us. It is Corsego's policy to respect your privacy regarding any information we may collect from you across our website,
  = succeed "," do
    %a{:href => "http://corsego.com"} http://corsego.com
%p We only ask for personal information when we truly need it to provide a service to you. We collect it by fair and lawful means, with your knowledge and consent. We also let you know why we’re collecting it and how it will be used.
%p We only retain collected information for as long as necessary to provide you with your requested service. What data we store, we’ll protect within commercially acceptable means to prevent loss and theft, as well as unauthorized access, disclosure, copying, use or modification.
%p We don’t share any personally identifying information publicly or with third-parties, except when required to by law.
%p Our website may link to external sites that are not operated by us. Please be aware that we have no control over the content and practices of these sites, and cannot accept responsibility or liability for their respective privacy policies.
%p You are free to refuse our request for your personal information, with the understanding that we may be unable to provide you with some of your desired services.
%p Your continued use of our website will be regarded as acceptance of our practices around privacy and personal information. If you have any questions about how we handle user data and personal information, feel free to contact us.
%p This policy is effective as of 24 April 2020.