config/routes.rb
Rails.application.routes.draw do

  #devise_for :users
  devise_for :users, :controllers => { registrations: 'users/registrations'}

  root 'home#index'
  get 'home/index'
  get 'activity', to: 'home#activity'
  get 'analytics', to: 'home#analytics'
  get 'privacy_policy', to: 'home#privacy_policy'

  resources :enrollments do
    get :my, on: :collection
  end
  resources :tags, only: [:create, :index, :destroy]

  resources :courses, except: [:edit] do
    get :learning, :pending_review, :teaching, :unapproved, on: :collection
    member do
      get :analytics
      patch :approve
      patch :unapprove
    end
    resources :lessons, except: [:index] do
      resources :comments, except: [:index]
      put :sort
      member do
        delete :delete_video
      end
    end
    resources :enrollments, only: [:new, :create]
    resources :course_wizard, controller: 'courses/course_wizard'
  end

  resources :users, only: [:index, :edit, :show, :update]

  resources :enrollments do
    get :my, on: :collection
    member do
      get :certificate
    end
  end

  namespace :charts do
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'course_popularity'
    get 'money_makers'
  end
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :course, counter_cache: true
  belongs_to :user, counter_cache: true

  validates :user, :course, presence: true

  validates_presence_of :rating, if: :review?
  validates_presence_of :review, if: :rating?

  validates_uniqueness_of :user_id, scope: :course_id  #user cant be subscribed to the same course twice
  validates_uniqueness_of :course_id, scope: :user_id  #user cant be subscribed to the same course twice

  validate :cant_subscribe_to_own_course  #user can't create a subscription if course.user == current_user.id

  scope :pending_review, -> { where(rating: [0, nil, ""], review: [0, nil, ""]) }
  scope :reviewed, -> { where.not(review: [0, nil, ""]) }
  scope :latest_good_reviews, -> { order(rating: :desc, created_at: :desc).limit(3) }

  extend FriendlyId
  friendly_id :to_s, use: :slugged

  def to_s
    user.to_s + " " + course.to_s
  end

  after_save do
    unless rating.nil? || rating.zero?
      course.update_rating
    end
  end

  after_destroy do
    course.update_rating
  end

  after_create :calculate_balance
  after_destroy :calculate_balance
  def calculate_balance
    course.calculate_income
    user.calculate_enrollment_expenses
  end

  protected
  def cant_subscribe_to_own_course
    if self.new_record?
      if self.user_id.present?
        if self.user_id == course.user_id
          errors.add(:base, "You can not subscribe to your own course")
        end
      end
    end
  end

end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:certificate]
  before_action :set_enrollment, only: [:show, :edit, :update, :destroy, :certificate]
  before_action :set_course, only: [:new, :create]

  def index
    #@enrollments = Enrollment.all
    #@pagy, @enrollments = pagy(Enrollment.all)


    @ransack_path = enrollments_path

    @q = Enrollment.ransack(params[:q])
    @pagy, @enrollments = pagy(@q.result.includes(:user))

    authorize @enrollments
  end

  def teaching
    @ransack_path = teaching_enrollments_path
    @q = Enrollment.joins(:course).where(courses: {user: current_user}).ransack(params[:q])
    @pagy, @enrollments = pagy(@q.result.includes(:user))
    render 'index'
  end

  def certificate
    authorize @enrollment, :certificate?
    respond_to do |format|
      format.pdf do
        render pdf: "#{@enrollment.course.title}, #{@enrollment.user.email}",
               page_size: 'A4',
               template: "enrollments/certificate.pdf.haml"
      end
    end
  end

  def show
  end

  def new
    @enrollment = Enrollment.new
  end

  def edit
    authorize @enrollment
  end

  def create

    if @course.price > 0

      @amount = (@course.price * 100).to_i
      customer = Stripe::Customer.create(
        email: params[:stripeEmail],
        source: params[:stripeToken]
      )
      Stripe::Charge.create(
        customer:    customer.id,
        amount:      (@course.price * 100).to_i,
        description: @course.title,
        currency:    'usd'
      )

      @enrollment = current_user.buy_course(@course)
      redirect_to course_path(@course), notice: "You are enrolled!"
    else
      @enrollment = current_user.buy_course(@course)
      redirect_to course_path(@course), notice: "You are enrolled!"
    end
    EnrollmentMailer.student_enrollment(@enrollment).deliver_later
    EnrollmentMailer.teacher_enrollment(@enrollment).deliver_later

    @enrollment = current_user.buy_course(@course)
    redirect_to course_path(@course), notice: "You are enrolled!"
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_course_enrollment_path(@course)
  end

  def update
    authorize @enrollment
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully updated.' }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @enrollment
    @enrollment.destroy
    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: 'Enrollment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_course
    @course = Course.friendly.find(params[:course_id])
  end

  def set_enrollment
    @enrollment = Enrollment.friendly.find(params[:id])
  end

  def enrollment_params
    params.require(:enrollment).permit(:rating, :review)
  end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_enrollment.html.haml
.card
  .card-header
    .fa.fa-user
    = link_to enrollment.user.username, user_path(enrollment.user)
    .fa.fa-clock
    = time_ago_in_words(enrollment.updated_at)
    .fa.fa-graduation-cap
    = link_to enrollment.course, course_path(enrollment.course)
  .card-body
    .text-warning.fa.fa-star
    %b= enrollment.rating
    .fa.fa-comment
    %small= enrollment.review
  - if current_user
    .card-footer
      - if policy(enrollment).edit?
        = link_to 'Edit Review', edit_enrollment_path(enrollment)

app/views/enrollments/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@enrollment) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :rating, collection: 1..5, as: :radio_buttons
    = f.input :review

  .form-actions
    = f.button :submit

app/views/enrollments/certificate.pdf.haml
%center
  %div{:style => "width:1200px; height:800px; padding:20px; text-align:center; border: 10px solid #563d7c"}
    %div{:style => "width:1150px; height:750px; padding:20px; text-align:center; border: 5px solid #563d7c"}
      %br
      %br
      %br
      %br
      %span{:style => "font-size:50px; font-weight:bold"} Certificate of Completion

      /%center
      /  %h1
      /    Certificate of Completion

      %br
      %br
      %br
      %br
      %p
      %h3
        This is to certify that the owner of the email address
      %h2
        %u
          = @enrollment.user.email
      %h3
        has successfully completed the course
      %h2
        %u
          = @enrollment.course.title
      %h3
        on the Corsego.com platform

      %p

      %br
      %br
      %br
      %br
      %b Certificate id:
      #{@enrollment.slug}

      %p

      %b Certificate url:
      #{request.base_url}#{request.original_fullpath}

      %p
      %b Registration date:
      #{@enrollment.created_at.strftime('%d-%b-%Y')}

      %br
      %br
      %br
      %center
        %h3
          = image_tag wicked_pdf_asset_base64('logo-bootstrap.png'), height: "30", width: "auto"
          %p
          www.Corsego.com

app/views/enrollments/edit.html.haml
- content_for :title do
  Corsego 
  \| 
  Editing
  = @enrollment.to_s

.card
  .card-header
    %h3
      .text-warning.fa.fa-star
      Add a Review
  .card-body
    = render 'form'
  .card-footer
    = link_to 'Show Review', @enrollment
    \|
    = link_to 'Back to course', course_path(@enrollment.course)

app/views/enrollments/index.html.haml
- content_for :title do
  Corsego
  |
  = action_name.humanize
  enrollments

%h3
  .text-center
    .fa.fa-lock-open
    = action_name.humanize
    enrollments
    .badge.badge-info
      = @enrollments.count
%p

= search_form_for @q, url: @ransack_path do |f|
  = f.search_field :user_email_cont, placeholder: 'user email'
  = f.search_field :course_title_cont, placeholder: 'course title'
  = f.search_field :course_user_email_cont, placeholder: 'teacher'
  = f.search_field :price_eq, placeholder: 'price'
  = f.search_field :rating_eq, placeholder: 'rating'
  = f.submit
= link_to 'refresh', @ransack_path

.table-responsive
  %table.table.table-bordered.table-striped.table-sm
    %thead
      %tr
        /%th ID
        %th
          = sort_link(@q, :user_email, "User")
          /.fa.fa-user
          /User
        %th
          = sort_link(@q, :created_at)
          /.fa.fa-clock
          /.fa.fa-lock-open
          /bought
        %th
          = sort_link(@q, :course_title, "Course")
          /.fa.fa-graduation-cap
          /Course
        %th Teacher
        %th
          = sort_link(@q, :price)
          /.fa.fa-dollar-sign
          /Price
        %th
          = sort_link(@q, :updated_at)
          .row
          .text-warning.fa.fa-clock
          Reviewed on
        %th
          = sort_link(@q, :rating)
          .text-warning.fa.fa-star
        %th
          .text-warning.fa.fa-comment
          Review
        %th Progress
        %th Certificate
        %th
        %th
        %th

    %tbody
      - @enrollments.each do |enrollment|
        %tr
          /%td= enrollment.id
          %td= link_to enrollment.user.email, user_path(enrollment.user)
          %td= enrollment.created_at.strftime("%d/%b/%Y, %H:%M")
          %td= link_to enrollment.course, course_path(enrollment.course)
          %td= link_to enrollment.course.user, user_path(enrollment.course.user)
          %td= number_to_currency(enrollment.price)
          %td
            - if enrollment.rating.present?
              = enrollment.updated_at.strftime("%d/%b/%Y, %H:%M")
          %td= enrollment.rating
          %td= enrollment.review
          %td= number_to_percentage(enrollment.course.progress(enrollment.user), precision: 0)
          %td= link_to 'Certificate', certificate_enrollment_path(enrollment, format: :pdf)
          %td= link_to 'See Review', enrollment
          %td
            - if policy(enrollment).edit?
              = link_to 'Add Review', edit_enrollment_path(enrollment)
          %td
            - if policy(enrollment).destroy?
              = link_to 'Delete Enrollment', enrollment, method: :delete, data: { confirm: 'Are you sure?' }
!= pagy_bootstrap_nav(@pagy)
%br

app/views/enrollments/new.html.haml
- content_for :title do
  Corsego
  |
  New enrollment

.card.shadow
  .card-header
    %h3
      .fa.fa-graduation-cap
      = link_to @course.title, course_path(@course)
      %hr
      .fa.fa-lock-open
      Buy course:
      = number_to_currency @course.price
  .card-body
    - if @course.price > 0
      = form_tag course_enrollments_path(@course) do
        %script.stripe-button{"data-amount" => "#{(@course.price * 100).to_i}",
                              "data-description" => "#{@course.title} (#{number_to_currency @course.price})",
                              "data-email" => "#{current_user.email}",
                              "data-key" => "#{Rails.application.credentials[Rails.env.to_sym][:stripe][:publishable]}",
                              "data-locale" => "auto",
                              :src => "https://checkout.stripe.com/checkout.js"}
    - else
      = form_tag course_enrollments_path(@course) do
        = submit_tag "Enroll for free!", class: 'btn btn-lg btn-success'
  .card-footer
    = link_to 'Back', course_path(@course)

app/views/enrollments/show.html.haml
= render 'enrollments/enrollment', enrollment: @enrollment

app/views/enrollments/show.pdf.haml
%center
  %div{:style => "width:1200px; height:800px; padding:20px; text-align:center; border: 10px solid #563d7c"}
    %div{:style => "width:1150px; height:750px; padding:20px; text-align:center; border: 5px solid #563d7c"}
      %br
      %br
      %br
      %br
      %span{:style => "font-size:50px; font-weight:bold"} Certificate of Completion

      /%center
      /  %h1
      /    Certificate of Completion

      %br
      %br
      %br
      %br
      %p
      %h3
        This is to certify that the owner of the email address
      %h2
        %u
          = @enrollment.user.email
      %h3
        has successfully completed the course
      %h2
        %u
          = @enrollment.course.title
      %h3
        on the Corsego.com platform

      %p

      %br
      %br
      %br
      %br
      %b Certificate id:
      #{@enrollment.slug}

      %p

      %b Certificate url:
      #{request.base_url}#{request.original_fullpath}

      %p
      %b Registration date:
      #{@enrollment.created_at.strftime('%d-%b-%Y')}

      %br
      %br
      %br
      %center
        %h3
          = image_tag wicked_pdf_asset_base64('logo-bootstrap.png'), height: "30", width: "auto"
          %p
          www.Corsego.com