config/routes.rb
Rails.application.routes.draw do

  #devise_for :users
  devise_for :users, :controllers => { registrations: 'users/registrations'}

  root 'home#index'
  get 'home/index'
  get 'activity', to: 'home#activity'
  get 'analytics', to: 'home#analytics'
  get 'privacy_policy', to: 'home#privacy_policy'

  resources :enrollments do
    get :my, on: :collection
  end
  resources :tags, only: [:create, :index, :destroy]

  resources :courses, except: [:edit] do
    get :learning, :pending_review, :teaching, :unapproved, on: :collection
    member do
      get :analytics
      patch :approve
      patch :unapprove
    end
    resources :lessons, except: [:index] do
      resources :comments, except: [:index]
      put :sort
      member do
        delete :delete_video
      end
    end
    resources :enrollments, only: [:new, :create]
    resources :course_wizard, controller: 'courses/course_wizard'
  end

  resources :users, only: [:index, :edit, :show, :update]

  resources :enrollments do
    get :my, on: :collection
    member do
      get :certificate
    end
  end

  namespace :charts do
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'course_popularity'
    get 'money_makers'
  end
end

app/controllers/courses/course_wizard_controller.rb
class Courses::CourseWizardController < ApplicationController
  include Wicked::Wizard
  before_action :set_progress, only: [:show, :update]
  before_action :set_course, only: [:show, :update, :finish_wizard_path]

  steps :landing_page, :targeting, :pricing, :lessons, :publish

  def show
    authorize @course, :edit?
    case step
    when :landing_page
    when :targeting
      @tags = Tag.all
    when :pricing
    when :lessons
    when :publish
    end
    render_wizard
  end

  def update
    authorize @course, :edit?
    case step
    when :landing_page
    when :targeting
      @tags = Tag.all
    when :pricing
    when :lessons
    when :publish
    end
    @course.update_attributes(course_params)
    render_wizard @course
  end

  def finish_wizard_path
    authorize @course, :edit?
    #courses_path
    course_path(@course)
  end

  private
  def set_progress
    if wizard_steps.any? && wizard_steps.index(step).present?
      @progress = ((wizard_steps.index(step) + 1).to_d / wizard_steps.count.to_d) * 100
    else
      @progress = 0
    end
  end

  def set_course
    @course = Course.friendly.find params[:course_id]
  end

  def course_params
    params.require(:course).permit(:title, :description, :short_description, :price,
                                   :published, :language, :level, :avatar, tag_ids: [],
                                   lessons_attributes: [:id, :title, :content, :_destroy]
    )
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:show]
  before_action :set_course, only: [:show, :edit, :update, :destroy, :approve, :unapprove, :analytics]

  def index
    @ransack_path = courses_path
    @ransack_courses = Course.published.approved.ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user, :course_tags, :course_tags => :tag))
    @tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc)
  end

  def learning
    @ransack_path = learning_courses_path
    @ransack_courses = Course.joins(:enrollments).where(enrollments: {user: current_user}).ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user, :course_tags, :course_tags => :tag))
    @tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc)
    render 'index'
  end

  def pending_review
    @ransack_path = pending_review_courses_path
    @ransack_courses = Course.joins(:enrollments).merge(Enrollment.pending_review.where(user: current_user)).ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user, :course_tags, :course_tags => :tag))
    @tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc)
    render 'index'
  end

  def teaching
    @ransack_path = teaching_courses_path
    @ransack_courses = Course.where(user: current_user).ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user, :course_tags, :course_tags => :tag))
    @tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc)
    render 'index'
  end

  def unapproved
    @ransack_path = unapproved_courses_path
    @ransack_courses = Course.unapproved.ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user, :course_tags, :course_tags => :tag))
    @tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc)
    render 'index'
  end

  def approve
    authorize @course, :approve?
    @course.update_attribute(:approved, true)
    redirect_to @course, notice: "Course approved and visible!"
  end

  def unapprove
    authorize @course, :approve?
    @course.update_attribute(:approved, false)
    redirect_to @course, notice: "Course upapproved and hidden!"
  end

  def analytics
    authorize @course, :owner?
  end

  def show
    authorize @course
    @lessons = @course.lessons.rank(:row_order)
    @enrollments_with_review = @course.enrollments.reviewed
  end

  def new
    @course = Course.new
    authorize @course
    @tags = Tag.all
  end

  def create
    @course = Course.new(course_params)
    authorize @course
    @course.description = 'Curriculum Description'
    @course.short_description = 'Marketing Description'
    @course.user = current_user

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_course_wizard_index_path(@course), notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        @tags = Tag.all
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @course
    if @course.destroy
      respond_to do |format|
        format.html { redirect_to teaching_courses_path, notice: 'Course was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to @course, alert: 'Course has enrollments. Can not be destroyed.'
    end
  end

  private
  def set_course
    @course = Course.friendly.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
  def enrollment_button(course)
    if current_user
      if course.user == current_user
        link_to course_path(course) do
          "You created this course " +
            number_to_currency(course.price)
        end
      elsif course.enrollments.where(user: current_user).any?
        link_to course_path(course) do
          "<i class='fa fa-spinner'></i>".html_safe + " " +
            number_to_percentage(course.progress(current_user), precision: 0)
        end
      elsif course.price > 0
        link_to number_to_currency(course.price), new_course_enrollment_path(course), class: 'btn btn-success'
      else
        link_to "Free", new_course_enrollment_path(course), class: 'btn btn-success'
      end
      #logic to buy
    else
      link_to "Check price", new_course_enrollment_path(course), class: "btn btn-md btn-success"
    end
  end

  def review_button(course)
    user_course = course.enrollments.where(user: current_user)
    if current_user
      if user_course.any?
        if user_course.pending_review.any?
          link_to edit_enrollment_path(user_course.first) do
            "<i class='text-warning fa fa-star'></i>".html_safe + " " +
              "<i class='text-dark fa fa-question'></i>".html_safe + " " +
              'Add a review'
          end
        else
          link_to enrollment_path(user_course.first) do
            "<i class='text-warning fa fa-star'></i>".html_safe + " " +
              "<i class='text-success fa fa-check'></i>".html_safe + " " +
              'Thanks for reviewing!'
          end
        end
      end
    end
  end

  def certificate_button(course)
    user_course = course.enrollments.where(user: current_user)
    if current_user
      if user_course.any?
        if course.progress(current_user) == 100
          link_to certificate_enrollment_path(user_course.first, format: :pdf) do
            "<i class='text-danger fa fa-file-pdf'></i>".html_safe + " " +
              "Certificate of Completion"
          end
        else
          "Certificate available after completion"
        end
      end
    end
  end
end

app/views/courses/_course.html.haml
.card
  .card-header
    .fa.fa-graduation-cap
    = link_to course.title, course_path(course)
  - if course.avatar.attached?
    .card-img-top
      = link_to course_path(course) do
        = image_tag course.avatar, height: "200px", width: "100%"
        /= image_tag course.avatar.variant(resize_to_limit: [100, 100])
  .card-footer
    %small= simple_format(course.short_description)
  .card-footer
    .text-center
      = enrollment_button(course)
      .row
      = review_button(course)
      .row
      = certificate_button(course)
  .card-footer
    .row
      .col-md-6
        .text-warning.fa.fa-star
        %b= course.average_rating
        /Enrollments count:
        /= course.enrollments.count
        /Counter cache enrollments count:
        (
        .fa.fa-user-graduate
        = course.enrollments_count
        )
        .fa.fa-tasks
        = course.lessons_count
      .col-md-6
        .text-right
          .fa.fa-chalkboard-teacher
          by
          = link_to course.user.username, user_path(course.user)
  - if current_user
    - if policy(course).owner?
      .card-footer
        = link_to 'Add lesson', new_course_lesson_path(course, @lesson), class: 'btn btn-primary btn-sm'
        = link_to course_course_wizard_index_path(course), class: 'btn btn-sm btn-warning mr-1' do
          .fa.fa-edit
          Editor
        = link_to analytics_course_path(course), class: 'btn btn-sm btn-info mr-1' do
          .fa.fa-chart-bar
          Analtycs
        - if policy(course).destroy?
          = link_to course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' do
            .fa.fa-trash
    - if policy(course).admin_or_owner?
      .card-footer
        - if course.published?
          .badge.badge-success published
        - else
          .badge.badge-danger unpublished
        - if course.approved?
          .badge.badge-success approved
        - else
          .badge.badge-danger unapproved
        - if policy(course).approve?
          - if course.approved?
            = link_to 'unapprove', unapprove_course_path(course), method: :patch, class: 'btn btn-sm btn-danger'
          - else
            = link_to 'approve', approve_course_path(course), method: :patch, class: 'btn btn-sm btn-success'
  - if course.tags.any?
    .card-footer
      - course.tags.each do |tag|
        .badge.badge-info
          = tag.name

app/views/courses/_form.html.haml
= simple_form_for(@course) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title, input_html: { autocomplete: 'off' }

  .form-actions
    = f.button :submit

app/views/courses/analytics.html.haml
- content_for :title do
  Corsego
  |
  = @course.title
  Analtycs

= link_to 'Courses', courses_path
|
= link_to course_path(@course) do
  .fa.fa-graduation-cap
  = @course.title
|
= link_to analytics_course_path(@course) do
  .fa.fa-chart-bar
  Analtycs

/%h4.text-center
/  Analtycs for #{@course.title}
%h4.text-center
  Enrollments per day, quantity
= line_chart @course.enrollments.group_by_day(:created_at).count

%h4.text-center
  Enrollments per day, revenue
= line_chart @course.enrollments.group_by_day(:created_at).sum(:price)

%h4.text-center
  Unique user views (how many unique users viewed the lesson)
= bar_chart @course.user_lessons.joins(:lesson).group(:'lessons.title').count

%h4.text-center
  Impressions per lesson (how many times the lesson was opened)
= bar_chart @course.user_lessons.joins(:lesson).group(:'lessons.title').sum(:impressions)

app/views/courses/index.html.haml
- content_for :title do
  Corsego
  \|
  = action_name.humanize
  courses

%h3
  .text-center
    .fa.fa-graduation-cap
    = action_name.humanize
    courses
    .badge.badge-info
      = @courses.count
%p

.row
  .col-lg-2
    /= search_form_for @q do |f|
    = search_form_for @ransack_courses, as: :courses_search, url: @ransack_path do |f|
      = f.label :title
      = f.search_field :title_cont, placeholder: 'Title', class: 'form-control form-control-sm'

      = f.label :tag
      = f.search_field :course_tags_tag_name_cont, placeholder: 'Tag name', class: 'form-control form-control-sm'

      = f.label :description
      = f.search_field :short_description_cont, placeholder: 'Description', class: 'form-control form-control-sm'
      = f.label :language
      .row
      = f.select :language_cont, Course.languages, include_blank: true
      .row
      = f.label :level
      .row
      = f.select :level_cont, Course.levels, include_blank: true
      .row
      = f.label :price
      = f.search_field :price_eq, placeholder: 'Price', class: 'form-control form-control-sm'
      = f.label :teacher
      = f.search_field :user_email_cont, placeholder: 'Email', class: 'form-control form-control-sm'
      .row
      = sort_link(@ransack_courses, :price)
      .row
      = sort_link(@ransack_courses, :average_rating, "Top Rated")
      .row
      = sort_link(@ransack_courses, :enrollments_count, "Most Popular")
      .row
      = sort_link(@ransack_courses, :created_at, "Fresh")
      .row
      = f.submit

    = link_to 'refresh', @ransack_path
    .row
    - @tags.each do |tag|
      /= link_to courses_path(courses_search: {course_tags_tag_id_eq: tag.id}) do
      = link_to controller: controller_name, action: action_name, courses_search: {course_tags_tag_id_eq: tag.id} do
        .badge.badge-info
          = tag.name
          %span.badge.badge-light
            = tag.course_tags_count
  .col-lg-10
    .card-columns
      - @courses.each do |course|
        = render 'courses/course', course: course
    /!= pagy_nav(@pagy)
    != pagy_bootstrap_nav(@pagy)
%br

app/views/courses/new.html.haml
- content_for :title do
  Corsego
  \|
  New course

.card
  .card-header
    %h3
      .fa.fa-graduation-cap
      New course
  .card-body
    = render 'form'
  .card-footer
    = link_to 'Back', courses_path

app/views/courses/show.html.haml
- content_for :title do
  Corsego
  |
  = @course.title

= link_to 'Courses', courses_path
|
= link_to course_path(@course) do
  .fa.fa-graduation-cap
  = @course.title

.row
  .col-lg-8.order-1.order-lg-1
    .jumbotron
      %h3
        .fa.fa-graduation-cap
        = @course.title
      %hr
      .fa.fa-clock
      Created
      = @course.created_at.strftime("%m/%Y")
      .row
      .fa.fa-clock
      Last updated
      = @course.updated_at.strftime("%m/%Y")
      .row
      .fa.fa-globe-africa
      = @course.language
      .row
      .fa.fa-signal
      = @course.level
      .row
      .fa.fa-file-pdf
      Certificate of Completion
      %hr
      = @course.description

    %h4
      .fa.fa-tasks
      = pluralize(@course.lessons_count, 'lesson')
      .float-right
        .fa.fa-spinner
        = number_to_percentage(@course.progress(current_user), precision: 0)
    %ul.list-group
      - @lessons.each do |lesson|
        %li.list-group-item
          = render 'lessons/lesson_preview', lesson: lesson
    %p

    %h4
      .fa.fa-comment
      = pluralize(@enrollments_with_review.count, 'review')
    - @enrollments_with_review.each do |enrollment|
      = render 'enrollments/enrollment', enrollment: enrollment
      %p


  .col-lg-4.order-0.order-lg-1
    .sticky-top
      = render 'courses/course', course: @course
    %p

%h4
  .fa.fa-graduation-cap
  Similar Courses

- Course.all.where.not(id: @course.id).each do |course|
  .row
  - unless @course.tags.pluck(:id).intersection(course.tags.pluck(:id)).count.zero?
    .card-columns
      = render 'courses/course', course: course